name: Release Build

on:
  push:
    tags:
      - "v*"

permissions:
  contents: write

jobs:
  build-linux-arm64:
    uses: ./.github/workflows/build-binary.yml
    with:
      goos: linux
      goarch: arm64
      runner: ubuntu-latest-arm64

  build-linux-amd64:
    uses: ./.github/workflows/build-binary.yml
    with:
      goos: linux
      goarch: amd64
      runner: ubuntu-latest-amd64

  build-darwin-arm64:
    uses: ./.github/workflows/build-binary.yml
    with:
      goos: darwin
      goarch: arm64
      runner: macos-latest

  build-darwin-amd64:
    uses: ./.github/workflows/build-binary.yml
    with:
      goos: darwin
      goarch: amd64
      runner: macos-13
  
  build-windows-amd64:
    uses: ./.github/workflows/build-binary.yml
    with:
      goos: windows
      goarch: amd64
      runner: windows-latest

  release:
    name: Create Release
    needs: [  build-linux-arm64, build-linux-amd64, build-darwin-arm64, build-darwin-amd64, build-windows-amd64 ]
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Download all artifacts
        uses: actions/download-artifact@v4
        with:
          path: ./artifacts

      - name: Create Release
        id: create_release
        uses: softprops/action-gh-release@v2
        with:
          name: Wavy WhatsApp CLI ${{ github.ref_name }}
          draft: false
          prerelease: false
          files: ./artifacts/**/*
          generate_release_notes: true
